name: CI


on: 
  push:
    branches: [master, dev]


jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
          nmake install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build/install-dir
        name: Windows
  

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Build
      run: |
          export CC=/usr/bin/gcc-13
          export CXX=/usr/bin/g++-13
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make install -j $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build/install-dir
        name: Linux


  windows-tests:
    runs-on: windows-latest
    needs: windows-build
    
    steps:
    - uses: actions/checkout@v4

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: Windows
        name: Windows
        
    - name: Tests
      working-directory: Tests
      run: |
          python tests.py


  linux-tests:
    runs-on: ubuntu-latest
    needs: linux-build
    
    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: Linux
        name: Linux
        
    - name: Tests
      working-directory: Tests
      run: |
          chmod +x ../Linux/LocalizationUtils
          python3 tests.py

  
  publish:
    runs-on: ubuntu-latest
    needs: [windows-tests, linux-tests]

    steps:
    - uses: actions/checkout@v4
  
    - uses: LazyPanda07/extract-current-branch@master
    
    - name: Setup release version variable
      shell: pwsh
      run: echo "VERSION=$($($($(Select-String -Path .\LocalizationUtils\src\Utility.cpp -Pattern version) -split '( = )')[3].TrimEnd(';')).Trim('\"'))" >> $Env:GITHUB_ENV

    - name: Download artifacts
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      uses: actions/download-artifact@v4
      
    - name: Create Windows zip
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      run: |
          cd Windows
          mv localization_utils_settings.json ../
          mv LocalizationUtils.exe ../
          rm -rf *
          mv ../localization_utils_settings.json .
          mv ../LocalizationUtils.exe .
          cd ..
          zip -r windows.zip Windows

    - name: Create Linux zip
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      run: |
          cd Linux
          mv localization_utils_settings.json ../
          mv LocalizationUtils ../
          rm -rf *
          mv ../localization_utils_settings.json .
          mv ../LocalizationUtils .
          cd ..
          zip -r linux.zip Linux

    - name: Publish Windows
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      uses: svenstaro/upload-release-action@master
      with:
        tag: v${{ env.VERSION }}
        file: Windows

    - name: Publish Linux
      if: ${{ env.CURRENT_BRANCH == 'master' }}
      uses: svenstaro/upload-release-action@master
      with:
        tag: v${{ env.VERSION }}
        file: Linux
